#!/bin/sh
set -x
cd VTK/build
cmake -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DVTK_BUILD_TESTING=OFF \
  -DVTK_BUILD_DOCUMENTATION=OFF \
  -DVTK_BUILD_EXAMPLES=OFF \
  -DVTK_WHEEL_BUILD=ON \
  -DVTK_PYTHON_VERSION=3 \
  -DVTK_WRAP_PYTHON=ON \
  -DVTK_DEFAULT_RENDER_WINDOW_HEADLESS=True \
  -DVTK_DATA_EXCLUDE_FROM_ALL:BOOL=ON \
  -DVTK_MODULE_ENABLE_VTK_PythonInterpreter:STRING=NO \
  -DVTK_OPENGL_HAS_EGL=False \
  -DVTK_OPENGL_HAS_OSMESA=True \
  -DVTK_USE_COCOA=FALSE \
  -DVTK_USE_X=FALSE \
  ..
set +x
