name: Build Wheel

on:
  pull_request:
  push:

jobs:
  build-vtk-osmesa:
    name: Build VTK with OSMesa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system requirements
        run: |
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends --yes \
              gcc \
              curl \
              git \
              cmake \
              ninja-build \
              build-essential \
              libosmesa6-dev \
              libxt-dev \
              libhdf5-dev \
              libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0 \
              libc6-dev libssl-dev libexpat1-dev \
          && \
          sudo rm -rf /var/lib/apt/lists/*
      - name: Download VTK
        run: |
          git clone https://github.com/Kitware/VTK.git VTK
          cd VTK
          git checkout v9.1.0
          mkdir build
      - name: Configure VTK
        run: |
          cd VTK/build && \
          cmake -GNinja \
          -DVTK_BUILD_TYPE=Release \
          -DVTK_BUILD_TESTING=OFF \
          -DVTK_BUILD_DOCUMENTATION=OFF \
          -DVTK_BUILD_EXAMPLES=OFF \
          -DVTK_WHEEL_BUILD=ON \
          -DVTK_PYTHON_VERSION=3 \
          -DVTK_WRAP_PYTHON=ON \
          -DVTK_DEFAULT_RENDER_WINDOW_HEADLESS=True \
          -DVTK_DATA_EXCLUDE_FROM_ALL:BOOL=ON \
          -DVTK_MODULE_ENABLE_VTK_PythonInterpreter:STRING=NO \
          -DVTK_OPENGL_HAS_EGL=False \
          -DVTK_OPENGL_HAS_OSMESA=True \
          -DVTK_USE_COCOA=FALSE \
          -DVTK_USE_X=FALSE \
          ..
      - name: Build VTK
        run: cd VTK/build && ninja
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtk-build
          path: VTK/build
      # Make wheel and upload as artifact for testing purposes
      - name: Build Test Wheel
        run: |
          pip install wheel && \
          cd VTK/build && \
          python setup.py bdist_wheel
      - name: Upload Test Wheel
        uses: actions/upload-artifact@v2
        with:
          name: vtk-osmesa-test-wheel
          path: VTK/build/dist/*.whl

  # Build wheel for all active Python versions
  build-wheels:
    name: OSMesa Wheel Building
    needs: build-vtk-osmesa
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - name: Install system requirements
        run: sudo apt-get install libosmesa6-dev libgl1-mesa-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        name: Download VTK Build Artifact
        with:
          name: vtk-build
          path: VTK/build
      - name: Build Wheel
        run: |
          pip install wheel && \
          cd VTK/build && \
          python setup.py bdist_wheel
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vtk-osmesa-wheel-py${{ matrix.python-version }}
          path: VTK/build/dist/*.whl
      - name: Install VTK and test import
        run: |
          pip install VTK/build/dist/*.whl
          python -c "import vtk; print('imported VTK')"
      - name: Install pyvista
        run: pip install pyvista
      - name: Test plot pyvista not off_screen
        run: python -c "import pyvista; pyvista.Sphere().plot(screenshot='screenshot.png');print('Plotted')"
      - name: Upload Test Screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot.png
          path: screenshot.png

  # Upload wheels to GH Pages package index
  # publish-wheels:
  #   name: Publish Wheels
  #   needs: build-wheels
  #   runs-on: ubuntu-latest
  #   steps:
  #     # TODO: upload wheels to GH pages with index file
