name: Unit Testing and Deployment

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

# simple action to verify we can import wheels in latest ubuntu
env:
  PYVISTA_OFF_SCREEN: true

jobs:

  osmesa:
    name: OSMesa Wheel Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install system requirements
        run: |
          sudo apt-get install libosmesa6-dev libgl1-mesa-dev

      - name: Install VTK and test import
        run: |
          pip install osmesa/vtk-9.1.0-cp38-cp38-linux_x86_64.whl
          python -c "import vtk; print('imported VTK')"

      - name: Install pyvista
        run: pip install pyvista

      - name: Test plot pyvista not off_screen
        run: python -c "import pyvista; pyvista.Sphere().plot();print('Plotted')"

      - name: Test Edge case
        run: python extract-edges.py

  osmesa-win:
    name: OSMesa Wheel Testing on Windows
    runs-on: windows-latest
    env:
      CI_WINDOWS: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install pyvista
        run: pip install pyvista

      - name: Install VTK and test import
        run: |
          pip uninstall vtk --yes
          pip install vtk_osmesa-9.2.20230328.dev0+mr76961-cp311-cp311-win_amd64.whl
          python -c "import vtk; print('imported VTK')"

      - name: Test plot pyvista not off_screen
        run: python -c "import pyvista; pyvista.Sphere().plot();print('Plotted')"

      - name: Test Edge case
        run: python extract-edges.py
